// WF4 — Build Follow-up Sequence (8-email)
// Build follow-up queue entries from actual Gmail sends (post-send truth).
// Source: Send via Gmail output — items that have a real Gmail message id.
// Cadence: stage 0 (email 1 sent) -> +3 business days; every later stage -> +7 calendar days (weekly).
//   This keeps the existing E1->E2 (3 biz) and E2->E3 (7 cal) timing and applies 7-day weekly for E4..E8.
// Stages 0..6 produce the next-stage row (queues emails 2..8). Stage 7 (email 8 sent) -> stop.
// EMPTY-BODY GUARD: never queue a stage whose target email body is blank. This protects legacy
//   3-email contacts (no email_4..8 generated by the old WF3) — they simply stop after email 3
//   instead of sending blank emails 4..8.

const results = [];
const now = new Date();

const addCalendarDays = (d, n) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r.toISOString().split('T')[0];
};

const addBusinessDays = (d, n) => {
  const r = new Date(d);
  let added = 0;
  while (added < n) {
    r.setDate(r.getDate() + 1);
    const dow = r.getDay();
    if (dow !== 0 && dow !== 6) added++; // skip weekends
  }
  return r.toISOString().split('T')[0];
};

// All 16 email fields carried forward on each follow-up row so the row is self-contained.
const EMAIL_FIELDS = [];
for (let i = 1; i <= 8; i++) {
  EMAIL_FIELDS.push('email_' + i + '_subject', 'email_' + i + '_body');
}

const sentItems = $('Send via Gmail').all();

for (const sentItem of sentItems) {
  // Filter: only real Gmail successes (has message id, no error)
  const gmailResp = sentItem.json;
  if (!gmailResp || gmailResp.error || !gmailResp.id) {
    continue;
  }

  // Back-reference original contact data via pairedItem
  let data;
  try {
    data = $('Prepare Send Fields').itemMatching(sentItem.pairedItem.item).json;
  } catch (e) {
    continue; // no matching source item — skip rather than fabricate
  }
  if (!data) continue;

  const stage = parseInt(data.follow_up_stage || '0', 10);
  const nextStage = stage + 1;
  if (nextStage > 7) continue; // email 8 was the last touch — sequence complete (WF6 picks up at stage 7)

  // The email that nextStage will send is email_(nextStage + 1). Guard against blank content.
  const nextBody = data['email_' + (nextStage + 1) + '_body'];
  if (!nextBody || !String(nextBody).trim()) continue; // legacy 3-email contact (or missing draft) — stop here

  const scheduled = (stage === 0) ? addBusinessDays(now, 3) : addCalendarDays(now, 7);

  const row = {
    opportunity_id: data.opportunity_id || '',
    contact_email: data.contact_email || '',
    contact_name: data.contact_name || '',
    company_name: data.company_name || '',
    company_domain: data.company_domain || '',
    job_title: data.job_title || '',
    location: data.location || '',
    approval_status: 'approved',
    sent_status: 'unsent',
    follow_up_stage: nextStage,
    scheduled_date: scheduled,
    posted_date: data.posted_date || '',
    source_url: data.source_url || ''
  };
  for (const f of EMAIL_FIELDS) row[f] = data[f] || '';

  results.push({ json: row });
}

return results;
